#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ASTD_PATH="../../astdlib/"
BASE_PARAMS="--no-application --no-cache --no-blanks --shellwrap -t node --no-map --path $ASTD_PATH -D version=0.1.10"
BUILD_PARAMS="$@ $BASE_PARAMS --time --base src/ --header ../LICENSE --out ../bin/ngadria.js main.adria"
TEST_PARAMS="$@ $BASE_PARAMS --base tests/ --assert --out test_all.js test_all.adria";

echo "changing working directory to $DIR"
cd $DIR
chmod +x ./bin/adria.js

echo "adria compiling ngadria..."
./bin/adria.js $BUILD_PARAMS

echo "ngadria compiling ngadria..."
./bin/ngadria.js $BUILD_PARAMS
md5sum ./bin/ngadria.js

echo "ok. again..."
./bin/ngadria.js $BUILD_PARAMS
md5sum ./bin/ngadria.js

echo "unit testing...";
./bin/ngadria.js $TEST_PARAMS
./tests/test_all.js
